#! /bin/sh

sxhkd &

sleep 1; xset -dpms &

xautolock -detectsleep \
		  -notify 120 -notifier "xset dpms force off" \
          -time     5 -locker   "i3lock-fancy -f Roboto-Medium" \
          -killtime 10 -killer   "systemctl suspend" \
          -corners -000 &

compton --config ~/.compton.conf &


~/.config/polybar/launch.sh &


xrandr --dpi 96&

dunst &

xsetroot -cursor_name left_ptr &

~/.fehbg &

systemctl --user start greenclip.service &

parcellite -n &

~/.config/bspwm/java_nonreparenting_wm_hack.sh &


#/usr/local/bin/lock -f Roboto &


#padding
bspc config top_padding     22
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       2
bspc config window_gap         6

# Borders and gaps
bspc config borderless_monocle true
bspc config gapless_monocle true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#FFFFFF" 
#B0BEC5
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#000000"

#presel color
bspc config presel_feedback_color "#B0BEC5"

# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

# Multihead behavior
#bspc config remove_disabled_monitors true
#bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity first_child

bspc monitor -d 1 2 3 4 5

